Repository WildCodeSchool-2023-09/JS-RMT-React_If-Projet3-GeoCode, pull requests merged in 2024-02, with the labels that each got.

#33 Menu card reserv
  backend/src/controllers/userControllers.js
  backend/src/router.js
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/assets/menuFaqPic.jpg
  frontend/src/assets/menuReservation.jpg
  frontend/src/components/HeaderHome.jsx
  frontend/src/components/MenuCards/MenuCardResa.jsx
  frontend/src/components/NavAdmin.css
  frontend/src/components/NavAdmin.jsx
  frontend/src/main.jsx
  frontend/src/pages/Reservation.jsx
Labels: Review Formateur

#35 Voiture f
  backend/public/assets/images/collec_1707215401116.jpg
  backend/public/assets/images/collec_1707216267972.jpg
  backend/public/assets/images/collec_1707216281783.jpg
  backend/public/assets/images/collec_1707216517085.jpg
  backend/public/assets/images/collec_1707216529107.jpg
  backend/src/controllers/carControllers.js
  backend/src/models/CarManager.js
  backend/src/router.js
  frontend/src/main.jsx
  frontend/src/pages/InsciptionCar.jsx
  frontend/src/pages/InsciptionVoiture.jsx
  frontend/src/pages/Inscription.jsx
  frontend/src/pages/Inscription_Profile.jsx
Labels: Review Formateur, MH en relecture

#37 Put terminal
  backend/public/assets/images/OIG (14)_1707141079398.jpg
  backend/public/assets/images/OIG (16)_1707140982187.jpg
  backend/public/assets/images/OIG (16)_1707230400075.jpg
  backend/public/assets/images/menuCardAdmin_1707214056478.jpg
  backend/src/controllers/terminalControllers.js
  backend/src/models/CarManager.js
  backend/src/models/ProfilManager.js
  backend/src/models/TerminalManager.js
  backend/src/router.js
  frontend/src/components/DisplayCards.css
  frontend/src/components/DisplayCardsId.jsx
  frontend/src/components/Inscription.css
  frontend/src/components/Map/MarkerComponent.jsx
  frontend/src/components/NavAdmin.css
  frontend/src/components/TerminalIdForm.jsx
  frontend/src/pages/Admin.css
  frontend/src/pages/AdminCarsId.jsx
  frontend/src/pages/AdminTerminalId.css
  frontend/src/pages/AdminTerminalId.jsx
  frontend/src/pages/AdminUserId.jsx
Labels: Review Formateur, MH en relecture

#36 Réservation
  backend/database/schema.sql
  backend/src/controllers/reservationControllers.js
  backend/src/models/CarManager.js
  backend/src/models/ReservationManager.js
  backend/src/router.js
  backend/src/tables.js
  frontend/src/components/Map/Map.css
  frontend/src/components/Map/Map.jsx
  frontend/src/components/Resa/Resa.css
  frontend/src/components/Resa/Resa.jsx
Labels: Review Formateur

#39 recuperation image enregister,modification du controllercar ,et prof…
  backend/database/terminal.js
  backend/public/assets/images/Design sans titre (3)_1707235093074.png
  backend/public/assets/images/borne.jpg
  backend/public/assets/images/collec_1707219942073.jpg
  backend/public/assets/images/collec_1707219955563.jpg
  backend/public/assets/images/collec_1707220005798.jpg
  backend/public/assets/images/collec_1707220017730.jpg
  backend/public/assets/images/collec_1707232620071.jpg
  backend/public/assets/images/collec_1707232636549.jpg
  backend/public/assets/images/collec_1707232786916.jpg
  backend/public/assets/images/collec_1707235000684.jpg
  backend/public/assets/images/collec_1707235217580.jpg
  backend/public/assets/images/collec_1707235230184.jpg
  backend/src/models/CarManager.js
  backend/src/models/ProfilManager.js
  frontend/src/components/CardItem.jsx
  frontend/src/components/CardItemId.jsx
Labels: Review Formateur

#42 Css
  backend/public/assets/images/cow-image-pixels-for-game-assets-vector-38164993_1707293984789.png
  backend/public/assets/images/eva_1707293999942.jpg
  backend/public/assets/images/reservation_1707293658251.jpg
  backend/public/assets/images/reservation_1707293677290.jpg
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/components/CardItem.css
  frontend/src/components/DisplayCards.css
  frontend/src/components/NavAdmin.css
  frontend/src/components/NavAdmin.jsx
  frontend/src/components/NavCard.css
  frontend/src/components/menuCard.css
  frontend/src/pages/Faq/FaqPage.css
Labels: Review Formateur

#41 Formulaire admin t
  backend/src/controllers/terminalControllers.js
  backend/src/models/TerminalManager.js
  backend/src/router.js
  frontend/src/components/TerminalIdForm.jsx
Labels: Review Formateur

#44 Affichage historique reservations
  frontend/src/components/Reservation/DisplayReserv.css
  frontend/src/components/Reservation/DisplayReserv.jsx
  frontend/src/main.jsx
  frontend/src/pages/Faq/FaqPage.css
  frontend/src/pages/Reservation.jsx
Labels: Review Formateur

#46 css des proptypes
  backend/public/assets/images/bmw_1707310873801.jpg
  backend/public/assets/images/profil2_1707310853928.jpg
  frontend/src/components/CardItem.css
  frontend/src/components/CardItemId.jsx
Labels: Review Formateur

#47 refait le seed end pour demo
  backend/database/car.js
  backend/database/profil.js
  backend/database/user.js
  backend/public/assets/images/bmw-serie3-jpeg.jpeg
  backend/public/assets/images/car2.jpg
  backend/public/assets/images/clio5-p3.jpg
  backend/public/assets/images/collec_1707219942073.jpg
  backend/public/assets/images/collec_1707219955563.jpg
  backend/public/assets/images/collec_1707220005798.jpg
  backend/public/assets/images/collec_1707220017730.jpg
  backend/public/assets/images/collec_1707232620071.jpg
  backend/public/assets/images/collec_1707232636549.jpg
  backend/public/assets/images/peugeot-308.jpg
  backend/public/assets/images/pexels-andrea-piacquadio.jpg
  backend/public/assets/images/photo-profil-p3.jpg
  backend/public/assets/images/photo-profil2-p3.jpg
  backend/public/assets/images/porsche-taycan.jpg
  backend/public/assets/images/profil1.jpg
  backend/public/assets/images/profil2.jpg
  backend/public/bmw.jpg
  backend/seed.js
  frontend/src/components/CardItem.jsx
Labels: Review Formateur

#48 Bdd reservation
  backend/database/schema.sql
  backend/public/assets/images/clio5-p3_1707317035373.jpg
  backend/public/assets/images/r_contact-ug_1707317010578.jpeg
  backend/src/controllers/reservationControllers.js
  backend/src/models/ReservationManager.js
  backend/src/router.js
  frontend/src/components/Resa/Resa.jsx
Labels: Review Formateur

#49 css et layout + lien page Fb
  frontend/src/App.jsx
  frontend/src/Layout.jsx
  frontend/src/components/Footer.jsx
  frontend/src/components/Map/Map.css
  frontend/src/components/Resa/Resa.css
  frontend/src/components/Reservation/DisplayReserv.css
  frontend/src/components/Reservation/DisplayReserv.jsx
  frontend/src/components/footer.css
  frontend/src/main.jsx
  frontend/src/pages/Faq/FaqPage.css
Labels: Review Formateur

#50 css fix
  backend/public/assets/images/bmw_1707326658420.jpg
  backend/public/assets/images/profil3_1707326631510.jpg
  frontend/src/components/Inscription.css
  frontend/src/components/NavAdmin.jsx
  frontend/src/components/footer.css
  frontend/src/pages/AdminTerminalId.css
  frontend/src/pages/Faq/FaqPage.css
Labels: Review Team
